AWSTemplateFormatVersion: 2010-09-09

Description: >
  devplatform-deploy certificate template version: v1.1.1
  Managed by dev-platform

Parameters:
  HostedZoneID:
    Description: Route53 Hosted Zone ID for domain validation
    Type: String
    Default: ""
  DomainName:
    Description: The base domain for this cert
    Type: String
  AddWWWPrefix:
    Description: Add a 'www' subdomain as a Subject Alternative Name
    Type: String
    Default: false
  AlternativeNameOne:
    Description: Subject Alternative Name One for the certificate
    Type: String
    Default: ""
  AlternativeNameTwo:
    Description: Subject Alternative Name Two for the certificate
    Type: String
    Default: ""
  AlternativeNameThree:
    Description: Subject Alternative Name Three for the certificate
    Type: String
    Default: ""
  AlternativeNameFour:
    Description: Subject Alternative Name Four for the certificate
    Type: String
    Default: ""
  AlternativeNameFive:
    Description: Subject Alternative Name Five for the certificate
    Type: String
    Default: ""
  AlternativeNameSix:
    Description: Subject Alternative Name Six for the certificate
    Type: String
    Default: ""
  AlternativeNameSeven:
    Description: Subject Alternative Name Seven for the certificate
    Type: String
    Default: ""
  AlternativeNameEight:
    Description: Subject Alternative Name Eight for the certificate
    Type: String
    Default: ""
  AlternativeNameNine:
    Description: Subject Alternative Name Nine for the certificate
    Type: String
    Default: ""
  AlternativeNameTen:
    Description: Subject Alternative Name Ten for the certificate
    Type: String
    Default: ""

Conditions:
  CreateWWWPrefix:  !Equals [true, !Ref AddWWWPrefix]
  CreateSansOne:  !Not [ !Equals ["", !Ref AlternativeNameOne ]]
  CreateSansTwo:  !Not [ !Equals ["", !Ref AlternativeNameTwo ]]
  CreateSansThree:  !Not [ !Equals ["", !Ref AlternativeNameThree ]]
  CreateSansFour:  !Not [ !Equals ["", !Ref AlternativeNameFour ]]
  CreateSansFive:  !Not [ !Equals ["", !Ref AlternativeNameFive ]]
  CreateSansSix:  !Not [ !Equals ["", !Ref AlternativeNameSix ]]
  CreateSansSeven:  !Not [ !Equals ["", !Ref AlternativeNameSeven ]]
  CreateSansEight:  !Not [ !Equals ["", !Ref AlternativeNameEight ]]
  CreateSansNine:  !Not [ !Equals ["", !Ref AlternativeNameNine ]]
  CreateSansTen:  !Not [ !Equals ["", !Ref AlternativeNameTen ]]
  CreateAltNames: !Or [Condition: CreateSansOne,
                       Condition: CreateSansTwo,
                       Condition: CreateSansThree,
                       Condition: CreateSansFour,
                       Condition: CreateSansFive,
                       Condition: CreateSansSix,
                       Condition: CreateSansSeven,
                       Condition: CreateSansEight,
                       Condition: CreateSansNine,
                       Condition: CreateSansTen]
  CreateSans: !Or [Condition: CreateWWWPrefix,
                   Condition: CreateAltNames]

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames: !If
        - CreateSans
        - - !If
            - CreateWWWPrefix
            - !Sub "www.${DomainName}"
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansOne
            - !Ref AlternativeNameOne
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansTwo
            - !Ref AlternativeNameTwo
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansThree
            - !Ref AlternativeNameThree
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansFour
            - !Ref AlternativeNameFour
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansFive
            - !Ref AlternativeNameFive
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansSix
            - !Ref AlternativeNameSix
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansSeven
            - !Ref AlternativeNameSeven
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansEight
            - !Ref AlternativeNameEight
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansNine
            - !Ref AlternativeNameNine
            - !Ref "AWS::NoValue"
          - !If
            - CreateSansTen
            - !Ref AlternativeNameTen
            - !Ref "AWS::NoValue"
        - !Ref "AWS::NoValue"
      ValidationMethod: DNS

Outputs:
  CertificateARN:
    Value: !Ref Certificate
    Description: Certificate ARN
    Export:
      Name: !Sub "${AWS::StackName}-CertificateARN"
