# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "activesupport", "~> 8.1"
gem "activesupport-duration-human_string", "~> 1.0"
gem "aws-sdk-codepipeline", "~> 1.111"
gem "concurrent-ruby", require: "concurrent"
gem "puma", "~> 7.1"
gem "rackup", "~> 2.3"
gem "sinatra", "~> 4.2"

group :development, :test do
  gem "libxml-ruby", "~>5.0.5"
  gem "rspec", "~> 3.13"
  gem "rubocop-govuk", "~> 5.1"
end
